#  security:
#    user:
#      roles: xxx
logging:
  level:
    liquibase: DEBUG
    org:
      liquibase: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger:
    default-server-url: "/"