spring:
  jpa:
    show-sql: true
    ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: schemakumpo
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always


#  security:
#    user:
#      roles: xxx
logging:
  level:
    liquibase: DEBUG
    org:
      liquibase: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger:
    default-server-url: "/"