spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: servitus
    hibernate:
      ddl-auto: update
    open-in-view: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-init-sql: SET search_path TO servitus
      max-lifetime: 480000            #8m
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000            #5m
      keepalive-time: 120000          #2m
      connection-timeout: 30000       #30s
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: servitus
  application:
    name: servitus
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: issuer
  profiles:
    active: localdb


management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /servitus

