server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: ./schema.sql
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:mem:kumpodb
    driver-class-name: org.h2.Driver


#  security:
#    user:
#      roles: xxx
logging:
  level:
    liquibase: DEBUG
    org:
      liquibase: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: swagger-ui.html
